eureka_odometry:
  ros__parameters:
    odometry_pub_topic: "~/odometry"
    twist_pub_topic: "~/twist_stamped"
    joint_sub_topic: "/wheel_states"
    imu_sub_topic: "/imu/data"
    enable_odom_tf: false
    wheel_radius: 0.15
    wheel_base: 0.76
    wheel_track: 1.00
    measure_error: 0.00